package: undo
version: '3.1.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/undo

requires:
    packages:
        structure: '^2.2.0'
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'
