package: undo
version: '2.0.3'
author: FriendsOfREDAXO
supportpage: github.com/FriendsOfREDAXO/undo

requires:
    packages:
        structure: '^2.2.0'
    redaxo: '^5.1.0'
    php:
        version: '>=5.6'
