package: undo
version: '2.1.3'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/undo

requires:
    packages:
        structure: '^2.2.0'
    redaxo: '^5.3.0'
    php:
        version: '>=5.6'
