package: undo
version: '3.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/undo

requires:
    packages:
        structure: '^2.2.0'
    redaxo: '^5.13.0'
    php:
        version: '>=7.4'
